### ISSUE TITLE
Can't stop screen recording

### ISSUE THREAD

**Issue by stefandesu** [FormidableLabs/clips#9]
When I try to stop the recording, I get this error on the console:

```
Uncaught TypeError: o is undefined
    d https://clips-plum.vercel.app/assets/index.aeeef80e.js:24
    Ys https://clips-plum.vercel.app/assets/index.aeeef80e.js:24
    xr https://clips-plum.vercel.app/assets/index.aeeef80e.js:4
    xr https://clips-plum.vercel.app/assets/index.aeeef80e.js:4
    cs https://clips-plum.vercel.app/assets/index.aeeef80e.js:5
[index.aeeef80e.js:24:25680](https://clips-plum.vercel.app/assets/index.aeeef80e.js)
```

Using Firefox 105.0.3 on macOS 12.5.1 (5K iMac from 2017). I also see a `Uncaught DOMException: MediaRecorder constructor: video/webm;codecs=vp9 indicates an unsupported codec` message when starting to record, so maybe that's the issue.

**Comment by gksander** [comment]
Just now seeing this! Interesting, I'll try to take a peak at this. Full honestly: I tested this primarily on Chromium-based browsers, and there are _certainly_ some x-browser incompatibilities when it comes to the media APIs 😅 

I hard-coded `video/webm;codecs=vp9` as a mime-type, but should realistically probably use a series of mime-type/codecs based on user's browser.
